### ISSUE TITLE
Android under 8(Oreo) not working

### ISSUE THREAD

**Issue by stepenik** [Keidan/SshServer#2]
This app works great on Android 8, but if you run this app on Android 7 or below app will be crashed. Do you know what is reason.

**Comment by Keidan** [comment]
This is probably due to the use of the notifications in the GUI that are not managed in the same way.

I can still make a modification to avoid crashes, which I couldn't test under Android 7 (I don't have it), but the behavior will not be the same.

However, I don't think I will support Android under version 7.

**Comment by stepenik** [comment]
I test this application on my Samsung s9 (8.0) Oreo and Samsung s8 (7.0) Nougat. And when I tried on S8 and when I click start server window is frozen and after that application crashed.
If you can make for Nougat will be cool 👍.

You can try run this app in GenyMotion emulator.

**Comment by Keidan** [comment]
Contrary to what I assumed above, the first error that causes the crash, is not related to notifications but to the non-implementation of the unmodifiableNavigableSet method (java.util.Collections JDK 1.8) in versions before Android 8.x.

This method is required by Apache MINA 2.0 (a subcall in the method org.apache.sshd.server.SshServer.setUpDefaultServer).

Android 7.x support requires an update of the MINA API and, to be honest, I'm not motivated to change this part (with the risk of creating other problems), especially since the application meets my needs under Android 8.x.

Nevertheless, I will ensure that the application no longer stops miserably.

**Comment by stepenik** [comment]
Ok thanks. Yes I also tried with sshd (0.14.0) version but for this version you need to change this part `setShellFactory`. But I don't know what will happen with JNI and NDK.

`sshd.setShellFactory(new ProcessShellFactory(new String[] { "/system/bin/sh", "-i", "-l" }));`

**Comment by stepenik** [comment]
In android 7 make snackbar pop-up if catch error in `org.apache.sshd.server.SshServer.setUpDefaultServer`. And this works correct 👍 

Did you try to replace SSHD Core 2.0.0 with 1.7.0 ? Maybe will work on Android 7 ?
https://mvnrepository.com/artifact/org.apache.sshd/sshd-core/1.7.0

**Comment by Keidan** [comment]
The initial problem is solved (crash) and the Android support being moved to another issue (#4), so I close here.
